Metrics/LineLength:
  Max: 600

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Lint/Loop:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 140

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 10

EndOfLine:
  Enabled: false