
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/UnifiedInteger:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Style/DateTime:
  Enabled: false
Style/Documentation:
  Enabled: false
