AllCops:
  TargetRubyVersion: 2.3

Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/UnifiedInteger:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Style/DateTime:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EvalWithLocation:
  Exclude:
    - 'lib/faker/json.rb'
Style/FrozenStringLiteralComment:
  Exclude:
    - 'lib/faker/json.rb'
    - 'test/test_faker_json.rb'
Style/For:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false

Security/Eval:
  Exclude:
    - 'lib/faker/json.rb'
